name: Secrets Scanner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  secrets_scanner:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Secrets Scanner
      uses: zaproxy/action-baseline@v0.12.0
      with:
        target: 'http://localhost'
        rules_file_name: '.zap/rules.xml'